export function usageText(): string {
  return [
    "Usage:",
    "  skill-suitcase plan --source <skills-repo> --target <target> --json",
    "  skill-suitcase diff --source <skills-repo> --target <target> --json",
    "  skill-suitcase pack --source <skills-repo> --target <target> --dry-run --json",
    "  skill-suitcase pack --source <skills-repo> --target <target> --output <dir> --json",
    "  skill-suitcase import --source <skills-repo> --json",
    "  skill-suitcase validate --source <skills-repo> --json",
    "  skill-suitcase validate --source <skills-repo> --strict --json",
    "  skill-suitcase targets --source <skills-repo> --json",
    "  skill-suitcase status --source <skills-repo> --json",
    "  skill-suitcase status --source <skills-repo> --target <target> --json",
    "  skill-suitcase apply --source <skills-repo> --target <target> --lock <path> --json",
    "  skill-suitcase apply --source <skills-repo> --target <target> --artifact <path> --json",
    "  skill-suitcase apply --source <skills-repo> --target <target> --lock <path> --mode symlink --json",
    "  skill-suitcase rollback --receipt <path> --json",
    "  skill-suitcase track --source <skills-repo> --target <target> [--skill <name> ...] --json",
    "  skill-suitcase reconcile --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --dry-run --json",
    "  skill-suitcase reconcile --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --apply --json",
    "  skill-suitcase repair --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --dry-run --json",
    "  skill-suitcase repair --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --apply --json",
    "  skill-suitcase promote --source <skills-repo> --target-skill <dir> --dry-run --json",
    "  skill-suitcase promote --source <skills-repo> --target-skill <dir> --apply --json",
    "",
    "Promote a target-created skill into the catalog (repo owns the source):",
    "  --target-skill <dir>   Path to the agent-home skill directory to promote",
    "  --dry-run              Read-only plan: report the workflow and any conflicts",
    "  --apply                Live promotion: copy, hash-verify, symlink back, receipt",
    "",
    "Target path overrides:",
    "  --codex-home <dir>     Override codex codexHome; skillsPath defaults to <dir>/skills",
    "  --codex-skills <dir>   Override codex skillsPath",
    "  --claude-skills <dir>  Override claude path"
  ].join("\n");
}
