export function usageText(): string {
  return [
    "Usage:",
    "  skill-suitcase plan --source <skills-repo> --target <target> --json",
    "  skill-suitcase diff --source <skills-repo> --target <target> --json",
    "  skill-suitcase pack --source <skills-repo> --target <target> --dry-run --json",
    "  skill-suitcase pack --source <skills-repo> --target <target> --output <dir> --json",
    "  skill-suitcase import --source <skills-repo> --json",
    "  skill-suitcase validate --source <skills-repo> --json",
    "  skill-suitcase validate --source <skills-repo> --strict --json",
    "  skill-suitcase targets --source <skills-repo> --json",
    "  skill-suitcase status --source <skills-repo> --json",
    "  skill-suitcase status --source <skills-repo> --target <target> --json",
    "  skill-suitcase apply --source <skills-repo> --target <target> --lock <path> --json",
    "  skill-suitcase apply --source <skills-repo> --target <target> --artifact <path> --json",
    "  skill-suitcase apply --source <skills-repo> --target <target> --lock <path> --mode symlink --json",
    "  skill-suitcase rollback --receipt <path> --json",
    "  skill-suitcase track --source <skills-repo> --target <target> [--skill <name> ...] --json",
    "  skill-suitcase reconcile --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --dry-run --json",
    "  skill-suitcase reconcile --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --apply --json",
    "  skill-suitcase repair --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --dry-run --json",
    "  skill-suitcase repair --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --apply --json",
    "  skill-suitcase promote --source <skills-repo> --target-skill <dir> --dry-run --json",
    "  skill-suitcase promote --source <skills-repo> --target-skill <dir> --apply --json",
    "  skill-suitcase import-target --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --dry-run --json",
    "  skill-suitcase import-target --source <skills-repo> --target <target> --skill <name> [--skill <name> ...] --apply --json",
    "  skill-suitcase upstream check --source <skills-repo> --json",
    "  skill-suitcase upstream fetch --source <skills-repo> --skill <name> --dry-run --json",
    "  skill-suitcase upstream import --source <skills-repo> --skill <name> --apply --json",
    "",
    "Import intentional local edits from a modeled target back into the catalog:",
    "  --target <target>      Modeled writable target whose dirty skill to import",
    "  --skill <name>         Skill to import (required; repeatable; no all-skills import)",
    "  --dry-run              Read-only plan: target/catalog paths, hashes, repo writes, refusals",
    "  --apply                Live import: copy the target skill into the catalog for review",
    "",
    "Promote a target-created skill into the catalog (repo owns the source):",
    "  --target-skill <dir>   Path to the agent-home skill directory to promote",
    "  --dry-run              Read-only plan: report the workflow and any conflicts",
    "  --apply                Live promotion: copy, hash-verify, symlink back, receipt",
    "",
    "Refresh catalog source from pinned upstream providers:",
    "  upstream check         Read-only report for declared upstream-managed skills",
    "  upstream fetch         Fetch into an isolated temp workspace and report catalog diff",
    "  upstream import        Copy fetched source into the catalog only; no target sync or commit",
    "",
    "Target path overrides:",
    "  --codex-home <dir>     Override codex codexHome; skillsPath defaults to <dir>/skills",
    "  --codex-skills <dir>   Override codex skillsPath",
    "  --claude-skills <dir>  Override claude path"
  ].join("\n");
}
